### ISSUE TITLE
[Feature Request] Option to use improved BLOCKMAP hit detection (outside of netplay/demos)

### ISSUE THREAD

**Issue by SirBofu** [kraflab/dsda-doom#125]
Woof currently has a PR for an optional gameplay option to use the improved BLOCKMAP hit detection as seen in International Doom. This is going to be an option that works regardless of complevel, but has to be turned on and is ignored when the game is in netplay or demo recording/demo playback to preserve compatibility.

https://github.com/fabiangreffrath/woof/pull/705

I think this would be an excellent QoL addition without causing any disturbances or forcing it upon users who would prefer the classic system. Even though DSDA-Doom is geared toward speedrunning, it would be an excellent QoL improvement for more casual play and is in line with other optional gameplay tweaks that are ignored during demo playback/recording, like freelook. Implementing it without tying it to a complevel also maximizes compatibility with WADs targeting specific complevels or players who prefer the gameplay in a specific complevel for one reason or another.

**Comment by kraflab** [comment]
As mentioned in the pr+ discussion:
> I don't consider it a problem to be fixed, and I don't want there to be such a critical difference between casual play and accurate play. There may be some legacy things like this that already existed and were inherited, but I don't plan to add more.

I would never have added freelook to dsda-doom but it's already there from pr+ and it's implementation was incorporated into heretic's vertical aiming when that game was merged. Jumping comes from hexen. I can understand that it may seem like a frivolous distinction, but turning on jumping as an option in doom is essentially a zero-cost feature because it's already there for hexen, and it's a required feature for future doom-in-hexen support, so it must exist. The blockmap change is something else.

Every feature costs time - even if you did it for me and created a PR, I would need to go through it. I'm particular about code structure and every line needs to be maintained. This port is in high flux, as it's not even at `1.0`. I am refactoring huge chunks of the code base all the time so it's not like ports that have mostly static chunks of code that will stay the same for a hundred years. That is to say, `more != good`, and I'm busy enough with all the things I want to add still as required features that something like this needs to have some special appeal for me to reprioritize it.
