### ISSUE TITLE
Voodoo dolls do not trigger music changer objects

### ISSUE THREAD

**Issue by T-117** [kraflab/dsda-doom#129]
It seems that voodoo dolls on conveyor belts do not trigger music change objects when they enter the sector the music change object is in.  If I clip into the area with the voodoo doll as the player character, the music change will trigger at that time.

**Comment by kraflab** [comment]
Music changes are not tied to the _game_ but to specific _players_. Rest assured that the voodoo doll is hearing the new music, but each player hears the music from the music changers that they themselves come across. This allows you for instance to have context-specific music that each player during coop hears distinctly, rather than having one player's location determine the music for both. Since this is working as intended, I will close the issue.

**Comment by T-117** [comment]
Hey, thanks for the quick response.  I get why you wouldn't want one player to trigger music for another.  What I'm having trouble understanding is why a player 1 start voodoo doll doesn't act as a trigger for player 1.  All other things like damage taken, weapon, health and power-up pickups all transfer to the player.  But music doesn't.  Being able to set music remotely has been a handy feature I've used with other source ports.  Admittedly, I may have been exploiting a bug.  But it seems like if co-op environment music was an issue, it's easy enough to not put music changer objects in voodoo doll closets.  Though if dsda doesn't want to support music change by voodoo doll, that's fine.  I will find a some sort of workaround.

**Comment by kraflab** [comment]
I can understand your point, but I don't choose how things behave. I merely implement the behaviour. Basically, it's not up to me to change how this works. You'd need to get all the ports to agree to make this the standard. If that's a conversation you want to have, I'll be happy to implement the change once it's decided - though this would make the behaviour only work for users with the latest versions. If it's important, you might prefer a workaround even in that case.
