### ISSUE TITLE
Error rendering sky in indexed light mode

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#155]
From @andrey-budko: With mlook and gamma correction (something with gld_DrawSkyCaps)

![image](https://user-images.githubusercontent.com/6490190/201213844-de2944a5-ea03-45dd-8304-0518ee3529ed.png)

**Comment by elim2g** [comment]
Looks like it has to do with how the sky strips are being rendered by being drawn above geometry - I think it may just be picking the wrong colour though? If you comment out the use of gld_DrawSkyCaps altogether the issue is still there but it's just undrawn buffer (at a quick glance). Happens looking directly down too (tested on the teleporter exit in map21 doom2)

**Comment by elim2g** [comment]
is gld_DrawSkyCaps just drawing gigantic sky planes to fill those gaps? Wouldn't that cause only the center texels of the texture to render to that space? I'm possibly misunderstanding here, just throwing out what I see

**Comment by yum13241** [comment]
Also, stretch/repeat short skies seems to be forcefully enabled which I personally don't like.

**Comment by bkoropoff** [comment]
What wad/map/location is this?

**Comment by andrey-budko** [comment]
doom2 map01 near the chainsaw
