### ISSUE TITLE
Spectres look a bit different in OpenGL

### ISSUE THREAD

**Issue by ghost** [kraflab/dsda-doom#167]
Hello.

In DSDA Doom, while playing Doom, spectres look a bit different to Vanilla.

PrBoom plus, has an option in OpenGL options called as *Thing Sprite Fuzz.*  When this is set to **Darken** spectres look as identical as in Vanilla Doom.

So, it would be cool if this port fixes this issue, in its future releases..

Thanks.

**Comment by kraflab** [comment]
There aren't any options in prboom+ related to spectres that are identical to vanilla doom. The particular set of options you are looking at actually display the whole sprite and are significantly different, which is why they were removed in dsda-doom. In other words, pr+ was actually the broken one and it was fixed in dsda-doom :^)

dsda-doom opengl fuzz is still not vanilla accurate, but it's not as bad as those options.

Since you are on the discord, I would recommend putting these kinds of comments there first - more people who know about these decisions are available to answer right away, and we can save some time :^)
