### ISSUE TITLE
Title music in DBP37 don't work with portmidi backend

### ISSUE THREAD

**Issue by rfomin** [kraflab/dsda-doom#177]
@ceski-1 changed the default SysEx reset in PrBoom+ because the GS reset requires "capital tone fallback" emulation. A quick fix is to change the default reset to `"gm"` here:https://github.com/kraflab/dsda-doom/blob/23a0633e7808a1bcd069fa5888f16f0e40431122/prboom2/src/dsda/configuration.c#L753

**Comment by kraflab** [comment]
There are a series of portmidi adjustments that still need to be brought in to dsda-doom:
https://github.com/coelckers/prboom-plus/commit/60ca146f5a1a9abe15f9c275c3bbe0189c500d4e
https://github.com/coelckers/prboom-plus/commit/a118c0d392761bc440ce6aab3dd561522d42b0ce
https://github.com/coelckers/prboom-plus/commit/ef89c5eced2c4d6dae9e22b7c233be52f8f0cbcb
https://github.com/coelckers/prboom-plus/commit/33021fe6953199e561c1ddaa77002d0b5f90f499

One of these changes that default, so it should fix it as well. @ceski-1 if you don't mind bringing dsda-doom up to speed I would appreciate it, but I imagine that kind of redundant work is annoying 😄 

Otherwise I'll get things sorted out for the next release :^)

**Comment by ceski-1** [comment]
I'll make a PR with the changes later today.

**Comment by ceski-1** [comment]
@rfomin This will be a good stress test wad for any future MIDI updates ([over 100 SysEx messages](https://user-images.githubusercontent.com/56656010/209448654-310fc353-13ed-40db-8a22-52baee6eefb1.png))
```
END OF THE DARK / POLICENAUTS                       for SC-88   
(c)1995 KONAMI ALL RIGHTS RESERVED.
```

**Comment by rfomin** [comment]
> This will be a good stress test wad for any future MIDI updates...

Also `D_RUNNIN` from the same WAD:
```
Title: One Night in NEO KOBE CITY (PC-Engine)
Copyright: (c)1995 KONAMI ALL RIGHTS RESERVED.
```
