### ISSUE TITLE
Empty space in widescreen on intermission is not always black in indexed mode

### ISSUE THREAD

**Issue by kraflab** [kraflab/dsda-doom#181]
Palette changes like invuln carry over into the intermission screen's side bars

**Comment by XaserAcheron** [comment]
Welp, the culprit here is the call to gld_LookupIndexedColor in gld_FillBlock -- it uses the current palette, i.e. pain or invuln or item flash.

That said, it's a bit sus that there isn't a call to reset the palette when the intermission screen is hit -- that seems like maybe the real trouble here.

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/428f18f3a943d4c51963f0ddd112a49b8b75e590

The colormap global was only being updated during player view rendering, hence it was not updated during intermission (even though the player's colormap field was correctly updated).
