### ISSUE TITLE
Upload to flathub.org

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#251]
This will make it easy to update and install since almost no Linux distros have dsda-doom packaged.

**Comment by kraflab** [comment]
This isn't an issue for this repo.

**Comment by mooreye** [comment]
So where?

**Comment by kraflab** [comment]
As with other distributions feel free to package and submit it yourself. Or otherwise you would want to find someone in that community that wants to do so. But this repository merely holds the code, it isn't responsible for distribution. You might want to talk to @fabiangreffrath since he has created a package for at least one distro. You could also try asking on the forums.

**Comment by fabiangreffrath** [comment]
Yes, right:
https://tracker.debian.org/pkg/dsda-doom
