### ISSUE TITLE
[Dev] Renderer Regression tests

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#252]
It's very difficult to determine if a change to the renderer has caused a regression without a lot of manual testing.  Vague outline of pie-in-the sky automated regression suite:

- Have a set of command line arguments that run a demo on a given wad until a given frame, then take a screenshot and exit
- Use this to generate test data against hand-picked wads that are known to be troublesome
- Regression suite automatically runs tests, compares screenshots against expected result
- Test everything against freedoom1/2 iwads and fetch pwads from idgames on demand to avoid copyright problems
- GL testing on headless Linux VMs/containers without hardware acceleration could be done with the Mesa LLVMPipe software GL implementation.

This could also automatically catch demo desyncs, etc.

**Comment by kraflab** [comment]
We already use extensive automated regression tests for demo syncing. It's the only way anything gets done :^)

There are some limited ones in the repo but KD has a more extensive test suite that runs overnight.

As far as renderer regression it's an interesting idea but I don't feel like it's worth the effort. For one thing how would you even go about creating a comprehensive test suite? And would it help? Recent bugs have been things that happen rarely and not deterministically. A solid test map would probably be a lot more useful.

**Comment by bkoropoff** [comment]
Hooking any existing regressions up to CI would be nice so GitHub complains about your PR if you break demos or whatever.  If there were a solid test map for rendering quirks (stencil.wad covers part of it), CI integration would have the same benefit.  Of course, this assumes a large enough influx of contributions to be worthwhile.

**Comment by kraflab** [comment]
Ya I understand conceptually why it would be nice, but it's just not worth it to me. And the regression tests take many hours to run, so either it would block PRs for too long or otherwise lack coverage, when it comes to demos. I don't believe we've ever broken demo compatibility with a release, so the process is working quite well - and generally I'm the only person touching code that affects compatibility, so I know when I want to check things - there are times where I know there are likely breaks but want to finish a round of changes before fixing them for instance.

**Comment by kraflab** [comment]
I will close this issue for now but we can reconsider this again at some point if it becomes essential.
