### ISSUE TITLE
gl rendering glitch on eternal.wad map02

### ISSUE THREAD

**Issue by andrey-budko** [kraflab/dsda-doom#256]
https://www.doomworld.com/idgames/themes/TeamTNT/eternal/eternal

broken after https://github.com/kraflab/dsda-doom/commit/35b26aad4c14f45f5eeff6f1e9d66c4c764e81b3 (r_bsp: bleed through very low floors as well)

![image](https://user-images.githubusercontent.com/6490190/224504376-ba1d47d3-f959-4ad5-8324-806491d54eb9.png)

**Comment by bkoropoff** [comment]
This weird structure is causing the problem:

![Screenshot from 2023-03-12 00-19-59](https://user-images.githubusercontent.com/2101303/224533542-a984c743-4e75-4107-83ad-793597df5404.png)

The sector bleeding it's detecting is correct (there is a missing lower texture which causes flat bleeding in software), but it should only apply to the small inner ring, not the rest of the room that shares a sector tag.

Even with the bleed logic commented out, this case is correctly handled by the stencil code.  Of course, turning bleed off re-breaks kdikdizd MAP15 and hr2 MAP01.  Is there some way to make stenciling handle those cases automatically as well and get rid of all the bleed hacks?  That would be cleaner.

Alternatively, bleeding needs to happen at the level of subsectors, to avoid false positives like these.  That would require #255 so we have subsector adjacency information available without GL nodes.  I'm guessing we'll also run into trouble with the GL rendering path drawing flats a sector at a time, as that PR mentions.

@kraflab, do you want to revert the bleeding changes for now or try to push forward?

**Comment by bkoropoff** [comment]
Actually, we probably don't need extra adjacency info to mark subsectors with bleed info.  The other thing is a problem, though.

**Comment by kraflab** [comment]
Reverting would put us back where we started at 0.25.6 I guess? I'd be interested in the answer to the stenciling question if that would make things cleaner overall. Otherwise the question would be if we cover more cases with the current code or the previous code.

**Comment by andrey-budko** [comment]
The stencil code was taken from GZDoom (hw_renderhacks.cpp / PrepareUnhandledMissingTextures), so the logic can be compared, but those places on Kdikdizd MAP15 and hr2 MAP01 are fine in gzdoom even with this feature disabled (gl_notexturefill 1)

**Comment by bkoropoff** [comment]
GZDoom is handling the kdikdizd case in hw_renderhacks.cpp / HandleMissingTextures, where a subsector is basically "assigned" to another sector across a sidedef with a missing bottom texture:

https://github.com/ZDoom/gzdoom/blob/master/src/rendering/hwrenderer/scene/hw_renderhacks.cpp#L626

It presumably avoids bugs like eternal MAP02 by doing the assignment at subsector granularity.  So it looks like we should do the same.

**Comment by bkoropoff** [comment]
General sketch of a fix with the current rendering structure (sector-at-a-time):

- Change gl_missingtexture.c to register sector-to-subsector bleeding rather than sector-to-sector
- Change gl_preprocess.c to break `sectorloops` into `sectorfloorloops`/`sectorceilingloops`.  Don't do GLU tessellation if a sector has any subsectors that are bleed targets.  If a subsector has occlusion bleeds registered, give its floor/ceiling loops to the bleed sector instead of its normal sector
- Change the rest of the GL path to use `sectorfloorloops`/`sectorceilingloops` and to register GL flats for floors and ceiling separately.
- Change r_bsp.c to use subsectors for bleed lookups, and to potentially register different sectors for the floor and ceiling of a subsector.  This will require breaking `gl_validcount` into two to separately track floor and ceiling.

This would be a lot easier if rendering was subsector-at-a-time:

- Always triangulate and render subsectors, get rid of `sectorloops`
- Keep `floorsector`/`ceilingsector` pointers in each `subsector_t` and use them to look up the visplanes.  Override them when detecting map tricks.  This could also handle fake sectors.

This would require being able to reliably render subsectors, though, which means we need a way to repair broken ones, fill holes, etc.

**Comment by bkoropoff** [comment]
Hmm, maybe this requires #255 after all.  If a subsector is marked as a bleed target, that needs to propagate to adjacent subsectors, which requires knowing what those are.

**Comment by kraflab** [comment]
@bkoropoff I got another report of another map that the bleedthrough fixes affected negatively. I guess we do need to roll back the progress since 0.25.6 :confused:

**Comment by bkoropoff** [comment]
Yeah, it seems like it's going to be very fiddly to make this case work.  The GL rendering path needs to be refactored to draw flats a subsector at a time (or at least something more granular than an entire sector).  The existing logic can be `#ifdef`ed out for now.

**Comment by kraflab** [comment]
Could you prepare a PR?
