### ISSUE TITLE
Certain keys do not work in languages that use an alphabet other than Latin.

### ISSUE THREAD

**Issue by ONETAPPYBOI** [kraflab/dsda-doom#322]
Example in the video below:
https://user-images.githubusercontent.com/82337417/230160575-006c3963-0052-4705-9c36-9b5cb948d93d.mp4

When I have my keyboard language on English, my bind to restore quick key frame set to `>` works as intended. However, when I switch my language to Ukrainian, a language that uses Cyrillic, the bind stops working. 

I specifically observed this behavior with the `< > ; [ ] ' ` keys. Also, the `/` key turns into the `>` key.

**Comment by kraflab** [comment]
Does setting `vanilla_keymap` to 1 fix anything for you? Otherwise this sounds like it's "working" to me, although it may not be what you expected. Another option is to set a second input profile and switch to that when you switch your keyboard layout. Basically you are changing where your keys are located when you switch keyboard layouts, so `>` is no longer `>`.

**Comment by ONETAPPYBOI** [comment]
Setting `vanilla_keymap` to 1 resolved the issue.

**Comment by kraflab** [comment]
Awesome 👍
