### ISSUE TITLE
[Dev] gl_main.c needs refactoring badly

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#337]
Functions like `gld_AddWall` in particular are a big pile of spaghetti.  There's even some non-error-handling `goto`s in there.

**Comment by kraflab** [comment]
There are many things that need refactoring, so I don't think we need an issue for this one 😄 
I agree it's an issue, I just don't want the issues tab to lose meaning, and it's already getting dangerously close to that point.

I refactor things as I go, and will go through the gl code at some point. While you could proactively refactor things, the problem is that it will basically take me as much time to review a refactoring PR as it would to do it myself (for anything non-trivial anyway), and I don't want to reach a point where PRs are gathering dust either. I can take a look at gl_main soon though if it's a major mess for you. By the way, these kinds of topics would be easiest to discuss quickly on discord rather than go through github issues, in the future, if you're on it 😄

**Comment by bkoropoff** [comment]
I wasn't aware there was a discord.

**Comment by bkoropoff** [comment]
@kraflab which discord server are you referring to?

**Comment by kraflab** [comment]
[Hell on Earth](https://discord.gg/ghWqUYu)
This discord is mainly about speedrunning but it's also where dsda-doom development is discussed. There's a lot of talk there about new features and issues, so it's especially a good place to find out about performance problems and more mysterious bugs, since most people won't bother making a github account to post stuff 😄 
Sometimes I mirror things on github but it depends on the scale of the issue and whether or not I know what I want to do about it yet.
