### ISSUE TITLE
Hangs on interrupt/crash on Linux (and maybe macOS)

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#342]
I noticed that dsda-doom would occasionally hang when hitting Ctrl-C to interrupt it.  It looks like this is because it registers a signal handler that calls [non-async-signal-safe](https://man7.org/linux/man-pages/man7/signal-safety.7.html) functions, e.g.:

- `vsnprintf`
- `snprintf`
- `fprintf`
- `strsignal`
- Anything registered via `I_AtExit`, e.g.
   - `glDeleteTextures` (`gl_detail.c`'s exit handler)
   - `free` (via `Z_Free`)
   - ...

POSIX signals can interrupt the program in literally any thread at any point during execution, with arbitrary locks or resources held or internal structures in an inconsistent state.  Even interrupting `fprintf` and then calling it again can hang on the mutex protecting the stdio buffers.

For `SIGINT`, it's best to set a variable and have the main loop call `I_SafeExit` at the next opportunity.  For anything else, it's probably better to register nothing at all and just let the process die unceremoniously on `SIGSEGV`, etc.

**Comment by kraflab** [comment]
The signal handler is there to ensure writing an ongoing demo whenever possible, even in the event of a crash, which is preferable to speedrunners. There are also times when users have reported crashes and they have a demo file that exactly reproduces the crash, making it easy to resolve. SIGINT is a special case though, is there a reason to have a signal handler for this at all?

**Comment by bkoropoff** [comment]
I'm not familiar with the demo recording code.  Are you just calling `fflush` in the handler, or are you writing a lot of manually buffered data?  It's best to write and flush data as soon as possible instead of trying to do it in a signal handler, which could just as well corrupt data instead.

**Comment by bkoropoff** [comment]
`SIGINT` should have a handler since it's the terminal equivalent of someone clicking the close button on your window or typing alt-f4, it just shouldn't do anything in the signal handler itself, but rather pass the event to the main loop.

**Comment by kraflab** [comment]
> I'm not familiar with the demo recording code. Are you just calling `fflush` in the handler, or are you writing a lot of manually buffered data? It's best to write and flush data as soon as possible instead of trying to do it in a signal handler, which could just as well corrupt data instead.

The demo is stored in a buffer until a complete demo is ready to be written. During play either casually or while recording tases it's possible to go backwards in time and also forward in time. This means it's completely normal to have cases where you have N branches of the buffer in memory simultaneously (e.g., you create a checkpoint at time 10, move back to time 7, record 3 frames forward, then restore the original checkpoint, meaning frames 7-10 now have the original inputs). It's also possible to write a demo immediately with the existing buffer to a separate file at any moment. Actually, every time a checkpoint is made there is a file written storing the whole state of the game, including the demo buffer, at that instant. Thus there's no getting around manually tracking the buffer(s).

As far as both manually tracking the buffers and also flushing data to files intermittently, I believe I tried this out with the required features and it did not work at all. I don't know enough about file write consistency rules but writing 7-10, then going back to 7 and writing 3 new frames led to inconsistencies in the data where the buffer was not always the latest version written. Since this would anyway add a lot of complexity and is not important in 99.99% of cases, I didn't continue pursuing it.

**Comment by kraflab** [comment]
> `SIGINT` should have a handler since it's the terminal equivalent of someone clicking the close button on your window or typing alt-f4, it just shouldn't do anything in the signal handler itself, but rather pass the event to the main loop.

You mentioned having the main loop deal with it, but how should it get back to the main loop? We don't know where in the middle of a frame the code received the signal, right? What about just calling I_SafeExit directly?

**Comment by bkoropoff** [comment]
> Since this would anyway add a lot of complexity and is not important in 99.99% of cases, I didn't continue pursuing it.

It would probably be doable with a memory mapped region, allowing you to treat the file as a big buffer and have any changes up to the point of the crash automatically committed to disk by the OS.  But yeah, it's probably too much work for the additional safety.

A less radical approach would be to use POSIX `open`/`write`/`close` to do I/O to the demo file.  These are all async-safe.  With some other refactoring to the signal handler path (e.g. using `write` instead of the `printf` family of functions to write an error message to the terminal), you could get something that's successful at dumping the demo in more circumstances than today.  Not sure how worth it is, though.

**Comment by bkoropoff** [comment]
> > `SIGINT` should have a handler since it's the terminal equivalent of someone clicking the close button on your window or typing alt-f4, it just shouldn't do anything in the signal handler itself, but rather pass the event to the main loop.
> 
> You mentioned having the main loop deal with it, but how should it get back to the main loop? We don't know where in the middle of a frame the code received the signal, right? What about just calling I_SafeExit directly?

You can set a variable (preferably a [`sig_atomic_t`](https://en.cppreference.com/w/c/program/sig_atomic_t)) and have the main loop check it.
