### ISSUE TITLE
Use ~/.config/dsda-doom instead of ~/.dsda-doom on linux

### ISSUE THREAD

**Issue by leia-uwu** [kraflab/dsda-doom#425]
i want my home directory to be clean :p

**Comment by Pedro-Beirao** [comment]
You can use ~/.dsda-doom, /usr/local/share/doom or any other folder with DOOMWADDIR

**Comment by fabiangreffrath** [comment]
This is about the config file path, I guess.

**Comment by leia-uwu** [comment]
yeah its about the config path

**Comment by fabiangreffrath** [comment]
There was code in prb+ for that.

**Comment by kraflab** [comment]
What about the people that currently use the port and have their config under ~/.dsda-doom?

**Comment by fabiangreffrath** [comment]
We could attempt to read the config from the legacy directory first, and delete it afterwards, but always save it to the new location.

**Comment by fabiangreffrath** [comment]
No wait. Try to read config from new location, if not found read from legacy location, always save to new location.

**Comment by leia-uwu** [comment]
hmm, just move old config to new config location if the old config directory exists and the new config directory doesn't?
i tried doing that myself but i am bad with C

**Comment by mooreye** [comment]
What about data files like autoload and IWADs? They would belong in `~/.local/share/dsda-doom` since they are user data, not configs?

**Comment by wongandj** [comment]
Piping in to say I still think this would be a good idea. Most unix (i.e. linux and macos) have done this change by reading and updating to the old `$HOME` files if they are already there, else R/Wing to `$XDG_*` if they are defined, else R/Wing to their default values (`$HOME/.config/dsda-doom`, `$HOME/.local/share/dsda-doom`, etc.)

Configs should go to `$XDG_CONFIG_HOME/dsda-doom`, app data (saves, tranmaps) should go to `$XDG_DATA_HOME/dsda-doom`.

I think that the user data like iwad search dir, etc. should continue to search in just current dir, then exe dir, then `$DOOMWADDIR` if it is defined, etc., since that is the expected behavior for doom ports. It would be better to define autoloads in the config rather than in a set directory, like gzdoom does, though an enhancement would be to allow users to specify autoloads with shell expansion, e.g. `"~/doom/autoloads/all-all/*"` instead of having to list each file to load verbatim like in GZDoom; maybe a colon-separated list of paths?

It would also be good to allow users to specify where save, etc. files should go in the config, like they can currently do with screenshots, which would override the previously mentioned search behavior.

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/38fc904d32f434a8ead3d8c815753fa13e9cdb70
