### ISSUE TITLE
Support blasphem.wad

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#462]
Support loading a IWAD named `blasphem.wad` to launch Heretic. Blasphemer is a Freedoom equivalent of Heretic: https://github.com/Blasphemer/blasphemer

**Comment by mooreye** [comment]
Currently dsda-doom crashes if you load just `blasphem.wad`. You have to either rename it to `heretic.wad` or load as PWAD after the original `heretic.wad`. Or you can use `-heretic` flag explicitly.

**Comment by kraflab** [comment]
As you mentioned, you can load alternate iwads by switching the engine with `-heretic`, so the wad is already supported. A separate question is "should dsda-doom use some heuristics to guess what game an iwad is for?", to which the answer is probably yes. I'll add that to my todo list, but I will close this issue since I don't intend to add "special" support for custom iwads.
